stages:
  - build
  - test

build:
  stage: build
  script:
  - export DATABASE_URL=postgres://postgres:@5432/python-test-app 
  - apt-get update -qy
  - apt-get install -y python3-dev python-pip
  - python3 
  only:
    - branches

test:python35:
    stage: test
    image: python:3.5
    script: 
    - pip install -r requirements.txt  
    - export PYTHONPATH=../
    - py.test -v --cov
