stages:
  - build
  - test

build:
  stage: build
  script: 
  - apt-get install python3-setuptools
  - python setup.py sdist
  only:
    - branches

test:python35:
    stage: test
    image: python:3.5
    script: 
    - pip install -r requirements.txt  
    - export PYTHONPATH=../
    - py.test -v --cov
